obj-$(CONFIG_ECTRL)          += ectrl.o
obj-$(CONFIG_SECO_CPLD_FW)   += cpld.o cgpio_expander.o lpc_bridge.o sio_w83627.o sio_w83627_gpio.o sio_w83627_serial.o
obj-$(CONFIG_SECO_PWR_BTN)   += pwrbutton_management.o
obj-$(CONFIG_BUZZER)         += pwm_generic.o
obj-$(CONFIG_BOARD_SECO_ID)  += board_id.o
